name: Build for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\go\pkg\mod
            C:\Users\runneradmin\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Build the application
        run: go build -o -ldflags='-s -w' discordtidal.exe cmd/main.go

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: discordtidal-windows
          path: discordtidal.exe
